name: Build Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: Build Version
        required: true
      skip_create_image:
        description: Skip the build image part for testing purposes
        default: "false"
        required: false
      image_name:
        description: The iamge to build 'azdo-agent' or 'github-runner'
        required: true

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    env:
      PKR_VAR_client_id: ${{ secrets.CLIENT_ID }}
      PKR_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
      PKR_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      PKR_VAR_resource_group: "rg-prod-we-images"
      PKR_VAR_version: ${{ github.event.inputs.version }}
      PKR_VAR_skip_create_image: ${{ github.event.inputs.skip_create_image }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          make build
