name: Release
on:
  release:
    types: [published]

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    env:
      PKR_VAR_client_id: ${{ secrets.CLIENT_ID }}
      PKR_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
      PKR_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      PKR_VAR_resource_group: "rg-prod-we-images"
      PKR_VAR_version: ${{ github.event.release.tag_name }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4.1.4
      - name: Build azdo-agent
        run: |
          make azdo-agent
      - name: Build github-runner
        run: |
          make github-runner
